// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteURLStmt, err = db.PrepareContext(ctx, deleteURL); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteURL: %w", err)
	}
	if q.getURLStmt, err = db.PrepareContext(ctx, getURL); err != nil {
		return nil, fmt.Errorf("error preparing query GetURL: %w", err)
	}
	if q.getURLByLongStmt, err = db.PrepareContext(ctx, getURLByLong); err != nil {
		return nil, fmt.Errorf("error preparing query GetURLByLong: %w", err)
	}
	if q.getUserURLsStmt, err = db.PrepareContext(ctx, getUserURLs); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserURLs: %w", err)
	}
	if q.storeURLStmt, err = db.PrepareContext(ctx, storeURL); err != nil {
		return nil, fmt.Errorf("error preparing query StoreURL: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteURLStmt != nil {
		if cerr := q.deleteURLStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteURLStmt: %w", cerr)
		}
	}
	if q.getURLStmt != nil {
		if cerr := q.getURLStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getURLStmt: %w", cerr)
		}
	}
	if q.getURLByLongStmt != nil {
		if cerr := q.getURLByLongStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getURLByLongStmt: %w", cerr)
		}
	}
	if q.getUserURLsStmt != nil {
		if cerr := q.getUserURLsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserURLsStmt: %w", cerr)
		}
	}
	if q.storeURLStmt != nil {
		if cerr := q.storeURLStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing storeURLStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db               DBTX
	tx               *sql.Tx
	deleteURLStmt    *sql.Stmt
	getURLStmt       *sql.Stmt
	getURLByLongStmt *sql.Stmt
	getUserURLsStmt  *sql.Stmt
	storeURLStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:               tx,
		tx:               tx,
		deleteURLStmt:    q.deleteURLStmt,
		getURLStmt:       q.getURLStmt,
		getURLByLongStmt: q.getURLByLongStmt,
		getUserURLsStmt:  q.getUserURLsStmt,
		storeURLStmt:     q.storeURLStmt,
	}
}
